---
title: Projects
description: |
  All publications with links to source code where available.
author: "Adi Cilik Pierewan"
date: 2023-04-26

layout: custom-standard

---

# Books

1.  **Adi Cilik Pierewan**. *[Analisis Data Sekunder Untuk Ilmu Sosial (1st
    Ed)](http://daris.netlify.app/)*. 2023.



# International Peer Reviewed Papers

(\* indicates undergraduate students)

1.  Sujarwoto Sujarwoto, Gindo Tampubolon & **Adi Cilik Pierewan**. (2017) Individual and Contextual Factors of Happiness and Life Satisfaction in a Low Middle Income Country. *Applied Research in Quality of Life*.
    [doi:
    10.1007/s11482-017-9567-y](https://link.springer.com/article/10.1007/s11482-017-9567-y).

2.  Sujarwoto Sujarwoto, Gindo Tampubolon & **Adi Cilik Pierewan**. (2017) A tool to help or harm? Online social media use and adult mental health in Indonesia. *International Journal of Mental Health and Addiction*.
    [doi:
    10.1007/s11469-019-00069-2](https://link.springer.com/article/10.1007/s11469-019-00069-2).

3.  **Adi Cilik Pierewan** & Gindo Tampubolon. (2015) Happiness and Health in Europe: A Multivariate Multilevel Model. *Applied Research in Quality of Life*.
    [doi: 10.1007/s11482-014-9309-3](https://link.springer.com/article/10.1007/s11482-014-9309-3).

4.  **Adi Cilik Pierewan** & Gindo Tampubolon. (2014) Spatial dependence multilevel model of well-being across regions in Europe. *Applied Geography*.
    [doi: 10.1016/j.apgeog.2013.12.005](https://www.sciencedirect.com/science/article/abs/pii/S0143622813002816).

5.  **Adi Cilik Pierewan** & Gindo Tampubolon. (2014) Internet Use and Well-Being Before and During the Crisis in Europe. *Social Indicators Research*.
    [doi: 10.1007/s11205-013-0535-0](https://link.springer.com/article/10.1007/s11205-013-0535-0).

6.  Emmanuel Nizeyumukiza, **Adi Cilik Pierewan**, Edmond Ndayambaje, Yulia Ayriza. (2020) Trust and well-being: Evidence from Indonesia. *Asian Social Work and Policy Review*.
    [doi:10.1111/aswp.12205](https://onlinelibrary.wiley.com/doi/abs/10.1111/aswp.12205).


7.  Emmanuel Nizeyumukiza, **Adi Cilik Pierewan**, Edmond Ndayambaje, Yulia Ayriza. (2020) Social Engagement and Retirement Satisfaction: Evidence from Indonesia. *Journal of Population and Social Studies*.
    [doi:10.25133/JPSSv28n3.015](https://so03.tci-thaijo.org/index.php/jpss/article/view/227699).


8.  Kismiantini; Ezra Putranda Setiawan;  **Adi Cilik Pierewan**; Montesinos-López, Osval Antonio. (2021) Growth Mindset, School Context, and Mathematics Achievement in Indonesia: A Multilevel Model. *Journal on Mathematics Education*.
    [doi:10.22342/jme.12.2.13690.279-294](https://ejournal.unsri.ac.id/index.php/jme/article/view/13690).

9.  Edmond Ndayambaje, **Adi Cilik Pierewan**, Emmanuel Nizeyumukiza,
Balthazar Nkundimana, Yulia Ayriza. (2020) Marital Status and Subjective Well-being: Does Education Level
Take Into Account?. *Cakrawala Pendidikan*.
    [doi:10.21831/cp.v39i1.29620](https://journal.uny.ac.id/index.php/cp/article/view/29620).

9.  Deri Indrahadi, Amika Wardana, **Adi Cilik Pierewan**. (2021) The prevalence of diabetes mellitus and relationship with socioeconomic status in the Indonesian population. *Cakrawala Pendidikan*.
    [doi:10.22146/ijcn.55003](https://journal.uny.ac.id/index.php/cp/article/view/29620).

10.  Susanti Susanti, **Adi Cilik Pierewan** ,
Kismiantini Kismiantini, and Sofjan Aripin. (2022) What Makes Indonesians Satisfied With
Their Health? A Multilevel
Analysis . *Sage Open*.
    [doi:10.1177/21582440221121722](https://journals.sagepub.com/doi/pdf/10.1177/21582440221121722).

## Other

1.  Gould R., **Çetinkaya-Rundel M.**, Zieffler A. (2013 - present)
    [Citizen-Statistician blog](http://citizen-statistician.org/)

2.  **Çetinkaya-Rundel M.**, Tackett M. (2020) [COVID-19 Data in the
    Classroom
    ](https://chance.amstat.org/2020/09/covid-19-in-the-classroom/),
    Chance Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 33, No. 3. [On
    GitHub](https://github.com/mine-cetinkaya-rundel/take-a-chance/tree/master/2020-07-classroom-covid19).

3.  **Çetinkaya-Rundel M.**, Tackett M. (2020) [From Drab to Fab:
    Teaching Visualization via Incremental
    Improvements](https://chance.amstat.org/2020/04/from-drab-to-fab/),
    Chance Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 33, No. 2. [On
    GitHub](https://github.com/mine-cetinkaya-rundel/take-a-chance/tree/master/2020-02-drab-to-fab).

4.  **Çetinkaya-Rundel M.** (2017) [DataFest Shows Spike in Growth,
    Provides Immersive
    Experience](http://stattrak.amstat.org/2017/09/01/datafestspike/),
    STATtrak.

5.  **Çetinkaya-Rundel M.**, Stangl D. (2017) [An Interview with Mine
    Çetinkaya-Rundel](https://chance.amstat.org/2017/04/interview-mine-cetinkaya-rundel/),
    Chance Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 30, No. 2.

6.  Rundel C., **Çetinkaya-Rundel M.**, (2016) [*La Quinta is Spanish
    for "Next to
    Denny's\"*](http://chance.amstat.org/2016/04/la-quinta/), Chance
    Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 29, No. 2.

7.  Gould R., Baumer, B., **Çetinkaya-Rundel M.**, Bray A. (2014) [*Big
    Data Goes to
    College*](http://magazine.amstat.org/blog/2014/06/01/datafest/),
    AMSTAT News. Issue 444.

8.  Behseta S., **Çetinkaya-Rundel M.** (2014) [*Interview with Jim
    Berger*](http://chance.amstat.org/2014/04/interview-with-berger/),
    Chance Magazine. Vol. 27, No. 2.

9.  McClintock S., **Çetinkaya-Rundel M.**, Stangl D.K. (2014) [*A
    Classroom Project for Generation
    Z*](http://chance.amstat.org/2014/11/classroom/), Chance Magazine
    Statistics Education Column, Taking a Chance in the Classroom. Vol.
    27, No. 4.

10. Bray A., **Çetinkaya-Rundel M.**, Stangl D.K. (2014) [*Five Concrete
    Reasons Your Students Should Be Learning to Analyze Data in the
    Reproducible
    Paradigm*](http://chance.amstat.org/2014/09/reproducible-paradigm/),
    Chance Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 27, No. 3.

11. Morgan K.L., **Çetinkaya-Rundel M.**, Stangl D.K. (2014) [*Speed
    Dating: Exploring Initial Romantic
    Attraction*](http://chance.amstat.org/2014/04/speed-dating/), Chance
    Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 27, No. 2.

12. McClintock S., **Çetinkaya-Rundel M.**, Stangl D.K. (2014) [*The
    Real Secret to Genius? Reading Between the
    Lines*](http://chance.amstat.org/2014/02/classroom-27-1/), Chance
    Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 27, No. 1.

13. Schutt R., Stangl, D.K., **Çetinkaya-Rundel M.** (2013) [*Embracing
    the Ambiguity and Potential of Data
    Science*](http://chance.amstat.org/2013/11/classroom-26-4/), Chance
    Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 26, No. 4.

14. **Çetinkaya-Rundel M.**, Stangl D.K. (2013) [*A Celebration of
    Data*](http://chance.amstat.org/2013/09/classroom_26-3/), Chance
    Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 26, No. 3.

15. **Çetinkaya-Rundel M.**, Morgan K.L., Stangl D.K. (2013) [*Looking
    Good on Course
    Evaluations*](http://chance.amstat.org/2013/04/looking-good/),
    Chance Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 26, No. 2.

16. Morgan K.L., **Çetinkaya-Rundel M.**, Stangl D.K. (2013) [*The
    American Community Survey*](http://chance.amstat.org/2013/02/acs/),
    Chance Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 26, No. 1.

17. **Çetinkaya-Rundel M.**, Stangl, D.K., Morgan K.L. (2012) [*Making
    the Old New
    Again*](http://chance.amstat.org/2012/11/chance-in-the-classroom-25-4/),
    Chance Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 25, No. 4.

18. **Çetinkaya-Rundel M.**, Stangl, D.K., Morgan K.L. (2012)
    [*Exploring Google's Transparency
    Report*](http://chance.amstat.org/2012/04/google/), Chance Magazine
    Statistics Education Column, Taking a Chance in the Classroom. Vol.
    25, No. 2.

19. Stangl D.K., **Çetinkaya-Rundel M.**, Morgan K.L. (2012) [*Uncounted
    Votes: A Case Study in Analyzing Aggregated
    Data*](http://chance.amstat.org/2012/02/taking-a-chance/), Chance
    Magazine Statistics Education Column, Taking a Chance in the
    Classroom. Vol. 25, No. 1.