---
title: "Subjective well-being dan kebijakan publik"
subtitle: "Alternatif pengukuran efektivitas kebijakan"
author: "Dr Susanti, Dr Sofjan Aripin, Adi Cilik Pierewan, Ph.D"
format: revealjs
---


## Rencana paparan



1. Tujuan



2. Sekilas tentang studi kebahagiaan



3. Dua streams kebahagiaan dan kebijakan publik



4. Bagaimana mengukur kebahagiaan?



5. Hasil kajian



6. Rekomendasi untuk kebijakan







## Mengapa perlu berfokus pada kebahagiaan?


1. Tujuan hidup manusia adalah bahagia: Aristoteles



2. Tujuan bangsa Indonesia sesuai Pembukaan UUD 1945: memajukan kesejahteraan umum


3. Raja Bhutan sudah memulai dengan Gross National Happiness 2008


4. Komisi Sarkozy 2008: Beyond GDP. Pengukuran kemajuan bangsa tidak hanya diukur dengan pertumbuhan ekonomi saja, namun indikator kesejahteraan lain harus diperhatikan termasuk indikator subjektif. 

5. PBB mulai mengadopsi pengukuran kebahagiaan sejak 2012


6. Menjadi salah satu indikator SDGs (Health and well-being). Kesejaheraan merupakan indikator SDGs nomor 4.


7. Pemerintah Indonesia perlahan menuju adopsi kebijakan tersebut dan diharapkan membantu meningkatkan kebahagiaan masyarakat.




## Masalah yang muncul di Indonesia


1. Pengukuran kebahagiaan atau pengukuran subjektif belum banyak diterima oleh pemerintah secara luas



2. Masih belum banyak kajian yang kuat mengenai kebahagiaan yang digunakan untuk kebijakan




## Tujuan


1. Menjajaki kemungkinan penggunaan kebahagiaan untuk kebijakan publik.

2. Mengidentifikasi pertanyaan yang relevan untuk mengukur efektivitas kebijakan publik.

3. Merekomendasikan beberapa pengukuran dan langkah untuk pengukuran kemajuan bangsa
